In [1]:
import pandas as pd
import csv
import re
import tensorflow
import numpy as np
from collections import Counter
import base64
import scipy.io as spio
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import torch
import matplotlib as plt
import os

os.system("pip install git+https://github.com/wookayin/tensorflow-plot.git@master")
import tfplot

Read the text file and create tensors from it
List comprehension to create a CSV file from the text file

In [ ]:
from posix import getcwd
print(getcwd())

In [2]:
file = ('ex1.txt')
with open(file, 'r') as f:
        lines = f.readlines()
        lines = [line.strip() for line in lines] #remove whitespace
        #Split the lines into words, words inside brackets are considered one word
        #create regex to split the lines into words based on either space or []
        #  but keep words inside [] together
        
        #lines = [re.split(r'(\[.*?\])', line) for line in lines]
        #lines = [re.split(r'(\().*?\))', line) for line in lines]
        lines = [line.split() for line in lines] #split the lines into words based on spaces
        lines = [line for line in lines if len(line) > 0] #remove empty lines
        lines = [line for line in lines if line[0] != '#'] #remove comments
        lines = [line for line in lines if line[0] != ''] #remove empty lines
        
        #Read the lists to CSV
        with open('ex1.csv', 'w') as f:
            writer = csv.writer(f)
            writer.writerows(lines)
        #read_file = pd.read_csv ([print(line) for line in lines])

Convert the CSV file's values to Numbers

In [3]:
num_words = 10000
tokenizer = Tokenizer(num_words=num_words, oov_token="<OOV>")
tokenizer.fit_on_texts(lines)
x_train = tokenizer.texts_to_sequences(lines)
bruh = np.array(x_train)
print(bruh)

[list([243, 244, 17, 2, 245, 246, 144, 247, 145, 248, 249, 146, 250, 251, 252, 253, 254, 255, 146, 145, 256, 257, 258])
 list([259, 260, 147, 2, 109, 66, 11, 110, 111, 261, 112, 24])
 list([262, 263, 80, 2, 147, 66, 11, 17, 113, 114, 264])
 list([265, 266, 24, 2, 17, 86, 67, 87, 88, 68, 89, 148, 149])
 list([267, 268, 17, 2, 24, 86, 67, 87, 88, 150, 89, 148, 151, 152, 153, 269])
 list([270, 271, 24, 2, 17, 4, 32, 61, 2, 62, 49, 34, 44, 7, 45, 35])
 list([272, 273, 17, 2, 24, 4, 32, 62, 2, 61, 50, 36, 34, 37, 44, 7, 45, 35])
 list([274, 275, 24, 2, 17, 4, 11, 61, 2, 62, 8, 38, 37, 44, 7])
 list([276, 277, 24, 2, 17, 86, 67, 87, 88, 68, 89, 154, 149])
 list([278, 279, 17, 2, 24, 86, 67, 87, 88, 150, 89, 154, 151, 152, 153, 280])
 list([281, 282, 24, 2, 17, 43, 155, 156, 157, 68])
 list([283, 284, 17, 2, 24, 43, 115, 156, 157, 41])
 list([285, 286, 24, 2, 17, 4, 287, 116, 288, 12, 13, 14, 5, 15, 16])
 list([289, 290, 24, 2, 17, 43, 291, 116, 158, 69, 68])
 list([292, 293, 17, 2, 24, 4, 11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """


#Padding and Truncating the data
        #The length of the logs needs to be the same for the algorithm to work
        #The algorithm will truncate the logs that are longer than the max length
        #The algorithm will pad the logs that are shorter than the max length
        #The max length is the average length of the logs + 2 standard deviations

In [4]:
max_length = int(np.mean([len(x) for x in x_train]) + 2*np.std([len(x) for x in x_train]))
x_train = pad_sequences(x_train, maxlen=max_length, padding='post', truncating='post')
breauh = np.array(x_train)
print(breauh)

[[243 244  17 ... 256 257 258]
 [259 260 147 ...   0   0   0]
 [262 263  80 ...   0   0   0]
 ...
 [947 948   3 ...   0   0   0]
 [950 951  19 ...  16   0   0]
 [953 954   2 ...   0   0   0]]


#Convert the numpy array to a tensor

In [5]:
tensor = tensorflow.convert_to_tensor(x_train, dtype=tensorflow.int32)
print(tensor)
#plt.plot(tensor) # easy and simple
#tf.plot(tensor)

tf.Tensor(
[[243 244  17 ... 256 257 258]
 [259 260 147 ...   0   0   0]
 [262 263  80 ...   0   0   0]
 ...
 [947 948   3 ...   0   0   0]
 [950 951  19 ...  16   0   0]
 [953 954   2 ...   0   0   0]], shape=(265, 23), dtype=int32)


Convert the tensor to COO format

Represent the Tensor more clearly

In [ ]:
tf_heatmap = tfplot.autowrap(breauh, figsize=(4, 4), batch=True)   # function: Tensor -> Tensor
plot_op = tf_heatmap(attention_maps)   # tf.Tensor shape=(?, 400, 400, 4) dtype=uint8
tf.summary.image("attention_maps", plot_op)